export enum ErrorCode {
  INVALID_MESSAGE = 'INVALID_MESSAGE',
  UNKNOWN_EVENT = 'UNKNOWN_EVENT',
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_ALREADY_ACTIVE = 'SESSION_ALREADY_ACTIVE',
  ORIGIN_REJECTED = 'ORIGIN_REJECTED',
  TOO_MANY_SESSIONS = 'TOO_MANY_SESSIONS',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  VAD_TIMEOUT = 'VAD_TIMEOUT',
  SESSION_TIMEOUT = 'SESSION_TIMEOUT',
  STT_ERROR = 'STT_ERROR',
  TRANSLATION_ERROR = 'TRANSLATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
